In [2]:
import pandas as pd
import os

In [3]:
data_dir='csv_files'
data_dir

'csv_files'

In [4]:
os.listdir(data_dir)

['202505-divvy-tripdata.csv',
 '202506-divvy-tripdata.csv',
 '202507-divvy-tripdata.csv',
 '202508-divvy-tripdata.csv',
 '202509-divvy-tripdata.csv',
 '202510-divvy-tripdata.csv',
 '202511-divvy-tripdata.csv',
 '202512-divvy-tripdata.csv',
 '202601-divvy-tripdata.csv',
 '202602-divvy-tripdata.csv',
 '202603-divvy-tripdata.csv',
 '202604-divvy-tripdata.csv']

In [5]:
all_df=[]
files=os.listdir(data_dir)
for filename in files:
    full_path=os.path.join(data_dir,filename)
    df=pd.read_csv(full_path)
    all_df.append(df)
combined_df=pd.concat(all_df)

In [6]:
len(combined_df)

5697455

In [7]:
combined_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BADF67E2C5058F19,classic_bike,2025-05-11 17:22:39.471,2025-05-11 18:11:19.249,DuSable Lake Shore Dr & North Blvd,LF-005,Winthrop Ave & Lawrence Ave,TA1308000021,41.911722,-87.626804,41.968812,-87.657659,member
1,0210AE485D59C8C5,electric_bike,2025-05-05 08:02:09.251,2025-05-05 08:12:07.549,Damen Ave & Grand Ave,TA1308000006,Desplaines St & Jackson Blvd,15539,41.892394,-87.676885,41.878119,-87.643948,member
2,5E68FE5B9283E4C4,classic_bike,2025-05-02 10:32:33.062,2025-05-02 10:39:07.262,LaSalle St & Illinois St,13430,Clark St & Elm St,TA1307000039,41.890762,-87.631697,41.903322,-87.632999,member
3,13D2DCD6FB872858,classic_bike,2025-05-12 11:12:16.579,2025-05-12 11:17:25.126,Milwaukee Ave & Rockwell St,13242,Damen Ave & Cortland St,13133,41.920330,-87.693090,41.915983,-87.677335,member
4,F04DF9EE163351DD,classic_bike,2025-05-01 10:13:36.821,2025-05-01 10:17:40.548,Halsted St & Roosevelt Rd,TA1305000017,Clinton St & Roosevelt Rd,WL-008,41.867324,-87.648625,41.867118,-87.641088,member

In [8]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5697455 entries, 0 to 448251
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 608.6+ MB

In [10]:
combined_df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1215745
start_station_id      1215745
end_station_name      1279863
end_station_id        1279863
start_lat                   0
start_lng                   0
end_lat                  5857
end_lng                  5857
member_casual               0
dtype: int64

In [13]:
combined_df['started_at']=pd.to_datetime(combined_df['started_at'])
combined_df['ended_at']=pd.to_datetime(combined_df['ended_at'])
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5697455 entries, 0 to 448251
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: datetime64[ns](2), float64(4), object(7)
memory usage: 608.6+ MB

In [16]:
combined_df['ride_length']=(combined_df['ended_at']-combined_df['started_at']).dt.total_seconds()/60

In [17]:
combined_df[['started_at','ended_at','ride_length']].head()

               started_at                ended_at  ride_length
0 2025-05-11 17:22:39.471 2025-05-11 18:11:19.249    48.662967
1 2025-05-05 08:02:09.251 2025-05-05 08:12:07.549     9.971633
2 2025-05-02 10:32:33.062 2025-05-02 10:39:07.262     6.570000
3 2025-05-12 11:12:16.579 2025-05-12 11:17:25.126     5.142450
4 2025-05-01 10:13:36.821 2025-05-01 10:17:40.548     4.062117

In [18]:
combined_df['ride_length'].describe()

count    5.697455e+06
mean     1.601657e+01
std      5.558202e+01
min     -5.479480e+01
25%      5.372267e+00
50%      9.395750e+00
75%      1.652692e+01
max      1.574900e+03
Name: ride_length, dtype: float64

In [20]:
clean_df=combined_df[combined_df['ride_length']>=1]
clean_df['ride_length'].describe()

count    5.541510e+06
mean     1.645690e+01
std      5.629568e+01
min      1.000000e+00
25%      5.665233e+00
50%      9.663633e+00
75%      1.683953e+01
max      1.574900e+03
Name: ride_length, dtype: float64

In [21]:
clean_df['day_of_week']=clean_df['started_at'].dt.day_name()

C:\Users\samsa\AppData\Local\Temp\ipykernel_17288\881733786.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['day_of_week']=clean_df['started_at'].dt.day_name()

In [22]:

clean_df = combined_df[combined_df['ride_length'] >= 1].copy()

clean_df['day_of_week'] = clean_df['started_at'].dt.day_name()

clean_df[['started_at', 'ride_length', 'day_of_week']].head()

               started_at  ride_length day_of_week
0 2025-05-11 17:22:39.471    48.662967      Sunday
1 2025-05-05 08:02:09.251     9.971633      Monday
2 2025-05-02 10:32:33.062     6.570000      Friday
3 2025-05-12 11:12:16.579     5.142450      Monday
4 2025-05-01 10:13:36.821     4.062117    Thursday

In [23]:
clean_df['ride_length'].max()

1574.9001833333334

In [24]:
clean_df['day_of_week'].mode()[0]

'Thursday'

In [25]:
clean_df.groupby('member_casual')['ride_length'].mean()

member_casual
casual    23.348868
member    12.691616
Name: ride_length, dtype: float64

In [26]:
clean_df.groupby(['member_casual','day_of_week'])['ride_length'].agg(['mean'],['count'])

                                mean
member_casual day_of_week
casual        Friday       23.146155
              Monday       23.132242
              Saturday     26.219344
              Sunday       27.072260
              Thursday     20.593037
              Tuesday      20.234710
              Wednesday    19.513044
member        Friday       12.628821
              Monday       12.340654
              Saturday     13.934547
              Sunday       13.943442
              Thursday     12.259725
              Tuesday      12.244051
              Wednesday    12.142511

In [27]:
order=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
clean_df['day_of_week']=pd.Categorical(clean_df['day_of_week'],categories=order, ordered=True)

In [29]:
clean_df.groupby(['member_casual','day_of_week'])['ride_length'].agg(['mean'],['count'])

C:\Users\samsa\AppData\Local\Temp\ipykernel_17288\3902725734.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  clean_df.groupby(['member_casual','day_of_week'])['ride_length'].agg(['mean'],['count'])

                                mean
member_casual day_of_week
casual        Monday       23.132242
              Tuesday      20.234710
              Wednesday    19.513044
              Thursday     20.593037
              Friday       23.146155
              Saturday     26.219344
              Sunday       27.072260
member        Monday       12.340654
              Tuesday      12.244051
              Wednesday    12.142511
              Thursday     12.259725
              Friday       12.628821
              Saturday     13.934547
              Sunday       13.943442

In [31]:
clean_df.groupby(['member_casual','day_of_week'], observed=False)['ride_length'].agg(['mean','count']).reset_index().sort_values(by='count', ascending=False)

   member_casual day_of_week       mean   count
10        member    Thursday  12.259725  589360
8         member     Tuesday  12.244051  569442
9         member   Wednesday  12.142511  567186
11        member      Friday  12.628821  527555
7         member      Monday  12.340654  503592
12        member    Saturday  13.934547  443284
5         casual    Saturday  26.219344  399124
13        member      Sunday  13.943442  383235
6         casual      Sunday  27.072260  326028
4         casual      Friday  23.146155  307758
3         casual    Thursday  20.593037  258903
0         casual      Monday  23.132242  224283
2         casual   Wednesday  19.513044  220920
1         casual     Tuesday  20.234710  220840

In [32]:
# 1. Verify the minimum ride length in our clean dataset
print(f"Minimum Ride Length: {clean_df['ride_length'].min()} minute")

# 2. Find the overall grand total count of rides for each user type
print("\n--- Grand Total Rides by User Type ---")
print(clean_df['member_casual'].value_counts())

Minimum Ride Length: 1.0 minute

--- Grand Total Rides by User Type ---
member_casual
member    3583654
casual    1957856
Name: count, dtype: int64

In [39]:
final_summary=clean_df.groupby(['member_casual','day_of_week'],observed=False)['ride_length'].agg(['mean','count']).reset_index().sort_values(by='count',ascending=False)
final_summary.to_csv('final_summary.csv',index=False)

In [36]:
bike_summary=clean_df.groupby(['member_casual','rideable_type']).size().reset_index(name='total_trips')
bike_summary.to_csv('bike_summary.csv',index=False)

In [38]:
#time summaries
clean_df['month']=clean_df['started_at'].dt.month_name()
clean_df['hour_of_day']=clean_df['started_at'].dt.hour
time_summary=clean_df.groupby(['member_casual','month','day_of_week','hour_of_day'],observed=False)['ride_length'].agg(['count','mean']).reset_index()
time_summary.columns=['member_casual', 'month', 'day_of_week', 'hour_of_day', 'total_trips', 'average_duration'] 
time_summary.to_csv('time-summary.csv', index=False)

In [46]:
# 1. Group by user type and starting station, pulling the coordinates and ride lengths
station_summary = clean_df.groupby(['member_casual', 'start_station_name'], observed=False).agg(
    start_lat=('start_lat', 'mean'),
    start_lng=('start_lng', 'mean'),
    total_trips=('ride_length', 'count'),
    average_duration=('ride_length', 'mean')
).reset_index()

# 2. Drop any rows where the station name might be missing/blank
station_summary = station_summary.dropna(subset=['start_station_name'])

# 3. Export the final map summary to a CSV file
station_summary.to_csv('station_summary.csv', index=False)